# Generated by Django 4.1.2 on 2026-03-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_en',
            field=models.TextField(blank=True, verbose_name='Resposta (EN)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Mensagem (EN)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título (EN)'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(verbose_name='Resposta'),
        ),
    ]
