# Generated by Django 3.2.6 on 2021-11-23 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ImageField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado'), (3, 'Recusado')], default=0, upload_to='', verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em ')),
                ('courso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrollments', to='cursos.cursos', verbose_name='Curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('usuario', 'courso')},
            },
        ),
    ]
