# Generated by Django 3.2.6 on 2021-11-23 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0002_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='courso',
            new_name='curso',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('usuario', 'curso')},
        ),
    ]
