# Generated by Django 3.2.6 on 2021-12-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20211213_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='anuncios', to='cursos.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='anuncios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentarios', to='cursos.anuncios', verbose_name='Anúncio'),
        ),
    ]
