# Generated by Django 3.2.10 on 2021-12-31 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_auto_20211228_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='anuncios',
            new_name='anuncio',
        ),
    ]
