# Generated by Django 3.2.10 on 2022-03-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_aulas_materiais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Disponível em'),
        ),
    ]
