# Generated by Django 6.0.3 on 2026-03-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_aulas_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='atualizado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='atualizado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em'),
        ),
    ]
