# Generated by Django 6.0.3 on 2026-03-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_cursos_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado'), (3, 'Recusado')], default=0, verbose_name='Situação'),
        ),
    ]
