# Generated by Django 6.0.3 on 2026-03-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='imagem',
            field=models.ImageField(blank=True, default='cursos/imagens/course-image.png', null=True, upload_to='cursos/imagens', verbose_name='Imagem'),
        ),
    ]
