# Generated by Django 4.1.2 on 2026-03-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_cursos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncios',
            name='conteudo_en',
            field=models.TextField(blank=True, verbose_name='Conteúdo (EN)'),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título (EN)'),
        ),
        migrations.AddField(
            model_name='aulas',
            name='descricao_en',
            field=models.TextField(blank=True, verbose_name='Descrição (EN)'),
        ),
        migrations.AddField(
            model_name='aulas',
            name='nome_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome (EN)'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='comentario_en',
            field=models.TextField(blank=True, verbose_name='Comentário (EN)'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='descricao_en',
            field=models.TextField(blank=True, verbose_name='Descrição Simples (EN)'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='nome_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome (EN)'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='sobre_en',
            field=models.TextField(blank=True, verbose_name='Sobre o Curso (EN)'),
        ),
        migrations.AddField(
            model_name='materiais',
            name='embutido_en',
            field=models.TextField(blank=True, verbose_name='Vídeo da aula (EN)'),
        ),
        migrations.AddField(
            model_name='materiais',
            name='nome_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome (EN)'),
        ),
    ]
